disabled = false
languageCode = "ko-KR"
languageName = "한국어"
weight = 1
title = "Sungbin Kim"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006-01-02"
  description = "Sungbin Kim의 개발 기록"

[params.author]
  name = "Sungbin Kim"
  email = "s_been@kakao.com"
  image = "img/profile.png"
  imageQuality = 96
  headline = "Android Developer"
  bio = "Android 개발과 학습 내용을 기록합니다."
  links = [
    { github = "https://github.com/KimSungBeen" },
  ]
