disabled = false
languageCode = "ko-KR"
languageName = "한국어"
weight = 1
title = "sbeenx.io"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/lamb-logo.png"
  description = "Sungbeen Kim의 개발 기록"

[params.author]
  name = "Sungbeen Kim"
  email = "s_been@kakao.com"
  image = "img/profile.png"
  imageQuality = 96
  headline = "Android Developer"
  bio = "Android 개발과 학습 내용을 기록합니다."
  links = [
    { github = "https://github.com/KimSungBeen" },
    { instagram = "https://www.instagram.com/do1and/" },
    { linkedin = "https://www.linkedin.com/in/sbeen" },
    { google = "mailto:sbeenx.io@gmail.com" },
    { email = "mailto:s_been@kakao.com" },
  ]
