disabled = false
languageCode = "ko-KR"
languageName = "í•œêµ­ì–´"
weight = 1
title = "sbeenx.io"

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/lamb-logo.png"
  logoLight = "img/lamb-logo-light.png"
  description = "Sungbeen Kimì˜ ê°œë°œ ê¸°ë¡"

[params.author]
  name = "Sungbeen Kim"
  email = "sbeenx.io@gmail.com"
  image = "img/profile.png"
  imageQuality = 96
  headline = 'ğŸ‡°ğŸ‡· Android developer <img src="/img/android-head.svg" alt="Android" style="display:inline-block;height:0.86em;width:auto;vertical-align:-0.1em;margin:0 0.08em;" /> Katsu lover <img src="/img/katsu.png" alt="Katsu" style="display:inline-block;height:1.05em;width:auto;vertical-align:-0.1em;margin:0 0.08em;" /> Manchester city fan <img src="/img/manchester-city-logo.png" alt="Manchester City" style="display:inline-block;height:1.05em;width:auto;vertical-align:-0.1em;margin:0 0.08em;" />'
  bio = "ë‚˜ì™€ ë™ë£Œì˜ ì‹œê°„ì„ ì ˆì•½í•˜ì."
  phone = "tel: 010-4034-6763"
  links = [
    { github = "https://github.com/KimSungBeen" },
    { instagram = "https://www.instagram.com/do1and/" },
    { linkedin = "https://www.linkedin.com/in/sbeen" },
    { google = "mailto:sbeenx.io@gmail.com" },
    { email = "mailto:s_been@kakao.com" },
  ]
