[[main]]
  name = "about"
  pageRef = "about"
  title = "about"
  weight = 5

[[main]]
  name = "resume"
  pageRef = "resume"
  title = "resume"
  weight = 6

[[main]]
  name = "blog"
  pageRef = "posts"
  title = "blog"
  weight = 10

[[main]]
  name = "projects"
  pageRef = "projects"
  title = "projects"
  weight = 15

[[main]]
  name = "tags"
  pageRef = "tags"
  title = "tags"
  weight = 20

[[footer]]
  name = "GitHub"
  url = "https://github.com/KimSungBeen"
  weight = 10
